// <auto-generated />
using System;
using AspnetCoreBasicArchitecture.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspnetCoreBasicArchitecture.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200501113914_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspnetCoreBasicArchitecture.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Code");

                    b.Property<DateTime>("DiteTime");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = new Guid("e92864cb-3da6-413d-9a75-45142bcd9e09"), Code = 1, DiteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Product1", Price = 12.3 },
                        new { Id = new Guid("bf57cbbc-a26c-43bd-900c-ebd12c174590"), Code = 2, DiteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Product2", Price = 45.8 },
                        new { Id = new Guid("7d69b489-a490-4317-be90-a2d411a65077"), Code = 3, DiteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Product3", Price = 36.9 },
                        new { Id = new Guid("afe5525a-b40b-4ff4-9640-784df6852b6b"), Code = 4, DiteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Product4", Price = 24.7 },
                        new { Id = new Guid("17e713a8-05f1-4694-a054-09375882c520"), Code = 5, DiteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Product5", Price = 13.9 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
